import './locales'
export { setupApi } from './api/setupApi'
export { useSetupStatus, SETUP_STATUS_KEY, type SetupStatusState } from './model/useSetupStatus'
export type { ISetupApi } from './model/ISetupApi'
export type { SetupStatus } from './model/types'
export { SetupCodeInvalidError, SetupAlreadyDoneError, KeyNotSavedError } from './model/errors'
export { SetupPage } from './ui/SetupPage'
