import './locales'

export type { ISpacesApi } from './model/ISpacesApi'
export { spacesApi } from './api/spacesApi'
export { SpacesApiProvider, useSpacesApi } from './model/spacesApiContext'
export { useMySpaces } from './model/useMySpaces'
export { useWritableSpaces } from './model/useWritableSpaces'
export { activeSpaceStore, LAST_SPACE_STORAGE_KEY } from './model/activeSpaceStore'
export { useActiveSpace } from './model/useActiveSpace'
export { useCurrentSpaceId } from './model/useCurrentSpaceId'
export type { CurrentSpace } from './model/useCurrentSpaceId'
export { SpaceSwitcher } from './ui/SpaceSwitcher'
export { useSpaceTimezone, spaceTimezoneOf } from './model/useSpaceTimezone'
